# Generated by Django 5.0.1 on 2024-02-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_profile_birthday_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
