# Generated by Django 5.0.1 on 2024-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
