# Generated by Django 5.0.1 on 2024-02-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='myfiles',
            field=models.BinaryField(null=True),
        ),
    ]
