# Generated by Django 5.0.1 on 2024-02-09 10:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_article_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
