# Generated by Django 5.0.1 on 2024-02-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_article_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='witer',
            new_name='writer',
        ),
    ]
