# Generated by Django 5.0.1 on 2024-02-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
