# Generated by Django 5.0.1 on 2024-02-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_comment_delete_testi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
