# Generated by Django 5.0.1 on 2024-03-31 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0025_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 15, 24, 46, 366099, tzinfo=datetime.timezone.utc)),
        ),
    ]
