# Generated by Django 5.0.1 on 2024-04-20 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0027_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 19, 39, 55, 954262, tzinfo=datetime.timezone.utc)),
        ),
    ]
