# Generated by Django 5.0.1 on 2024-04-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0036_alter_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 19, 50, 28, 807941, tzinfo=datetime.timezone.utc)),
        ),
    ]
