# Generated by Django 5.0.1 on 2024-04-20 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0040_alter_article_slug_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 20, 26, 39, 518871, tzinfo=datetime.timezone.utc)),
        ),
    ]
