# Generated by Django 5.0.1 on 2024-05-09 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0050_alter_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 18, 16, 51, 752762, tzinfo=datetime.timezone.utc)),
        ),
    ]
