# Generated by Django 5.0.1 on 2024-05-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0051_alter_article_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
    ]
