# Generated by Django 5.0.1 on 2024-05-16 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0052_remove_article_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 7, 1, 16, 145988, tzinfo=datetime.timezone.utc)),
        ),
    ]
